name: ${project.name}
version: ${project.version}
build: ${buildNumber}
main: ${main.class}
author: ${author}
api-version: 1.16
load: STARTUP
loadbefore:
  - Vault

softdepend:
  - PlaceholderAPI

libraries:
  - org.yaml:snakeyaml:1.30